// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApqiZhjY9C1gpCBjbaysHPKOh7d09O73c',
    appId: '1:584264367901:web:55ca8d4acb3e8954b96bf4',
    messagingSenderId: '584264367901',
    projectId: 'king-jim-tepra-smartphone-in',
    authDomain: 'king-jim-tepra-smartphone-in.firebaseapp.com',
    storageBucket: 'king-jim-tepra-smartphone-in.firebasestorage.app',
    measurementId: 'G-EF4XJYZ2C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hgi2fKP6Ie_1ftGK6d725ykqQOThKvw',
    appId: '1:584264367901:android:714e99419925d333b96bf4',
    messagingSenderId: '584264367901',
    projectId: 'king-jim-tepra-smartphone-in',
    storageBucket: 'king-jim-tepra-smartphone-in.firebasestorage.app',
  );
}
